# Generated by Django 5.2.11 on 2026-03-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_job_player"),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Weapon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("attack", models.IntegerField()),
                ("character", models.ManyToManyField(to="game.character")),
            ],
        ),
    ]
