# Generated by Django 5.2.11 on 2026-03-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_character_weapon"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("age", models.IntegerField(default=0)),
                ("hobby", models.CharField(max_length=50)),
            ],
        ),
    ]
